# https://taskfile.dev
version: '3'
vars:
  BINFILE: gitlab-mcp

tasks:
  default:
    desc: "List all tasks"
    cmds:
      - task -a

  build:
    desc: "Build the binary"
    cmds:
      - go mod download
      - CGO_ENABLED=0 go build -o {{.BINFILE}} .

  linter:
    desc: "Run linter"
    cmds:
      - golangci-lint run

  # image:
  #   desc: "Build/push the docker image version latest"
  #   cmds:
  #     - docker build . -t ghcr.io/sgaunet/{{.BINFILE}}:latest --push

  snapshot:
    desc: "Create a snapshot release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --snapshot

  release:
    desc: "Create a release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --skip validate

  test:
    desc: "Run unit tests"
    cmds:
      - go test ./internal/... -v

  coverage:
    desc: "Generate coverage report with percentage"
    cmds:
      - go test ./internal/... -coverpkg=./internal/... -coverprofile=profile.cov
      - echo -n "Total Coverage{{":"}} "
      - go tool cover -func profile.cov | grep '^total{{":"}}' | awk '{print $3}'
      - rm -f profile.cov

